language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly-2016-06-07
  - nightly
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    sources:
    - travis-ci/sqlite3
    - ubuntu-toolchain-r-test
    packages:
    - sqlite3
    - gcc-5
    - g++-5
env:
  - CXX=g++-5 CC=gcc-5
cache:
  cargo: true
  apt: true
  directories:
  - $HOME/libsodium
  - $HOME/capnp

install:
  - ./travis-install-libsodium.sh
  - ./travis-install-capnp.sh
  - export PKG_CONFIG_PATH=$HOME/libsodium/lib/pkgconfig:$HOME/capnp:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=$HOME/libsodium/lib:$HOME/capnp:$LD_LIBRARY_PATH
  - export PATH=$HOME/capnp/bin:$PATH

script:
  - cargo build --verbose
  - RUST_LOG=error cargo test --verbose
  - 'if [[ "$TRAVIS_RUST_VERSION" == nightly* ]]; then RUST_LOG=error cargo test --verbose --features benchmarks; fi'
  - cargo doc
