[package]
authors = ["Johan Nielsen <sejr@google.com>"]
build = "build.rs"
name = "hat-backup"
version = "0.0.1-pre"

[profile.release]
debug = true

[lib]
name = "hat"
path = "src/lib.rs"

[[bin]]
name = "hatbin"
path = "src/main.rs"

[build-dependencies]
capnpc = "*"

[dependencies]
byteorder = "*"
capnp = "*"
clap = "*"
env_logger = "*"
error-type = "0.1.2"
libsodium-sys = "*"
log = "*"
quickcheck = "*"
rand = "*"
rustc-serialize = "*"
sodiumoxide = "*"
time = "*"
void = "1"
scoped-pool = "*"


[dependencies.diesel]
default-features = false
features = ["sqlite"]
version = "^0.11.4"

[dependencies.diesel_codegen]
default-features = false
features = ["sqlite"]
version = "^0.11.0"

[features]
default = []

# Running our benchmarks currently requires
# running on nightly. Use this feature to enable
# the code for this.
benchmarks = []
